# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric
minecraft_version=26.3
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod
mod_version=1.4.1+26.3
mc_range=>=26.3
maven_group=com.wywf
archives_base_name=wywf

# Fabric API
fabric_api_version=0.160.5+26.3

# Optional dependencies
yacl_version=3.9.6
yacl_mc_version=26.3
modmenu_version=20.0.1